#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
const tello = require('tello')
const joanna = require('joanna')

const rootDir = path.join(__dirname, '..')

const sourceDir = 'src'
const jsFiles = []
for (const entry of fs.readdirSync('src')) {
  if (entry.endsWith('.js')) {
    jsFiles.push(path.join(sourceDir, entry))
  }
}

const jsMetadata = joanna(jsFiles)
const docs = tello.digest([jsMetadata])
fs.writeFileSync(path.join(rootDir, 'api.json'), JSON.stringify(docs, null, 2))
