name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node_arch:
          - x64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          architecture: ${{ matrix.node_arch }}
      - name: Install Python setuptools (Unix-likes)
        # This is needed for Python 3.12+, since many versions of node-gyp
        # are incompatible with Python 3.12+, which no-longer ships 'distutils'
        # out of the box. 'setuptools' package provides 'distutils'.
        if: ${{ runner.os != 'Windows' }}
        run: python3 -m pip install --break-system-packages setuptools
      - name: Install Python setuptools (Windows)
        # This is needed for Python 3.12+, since many versions of node-gyp
        # are incompatible with Python 3.12+, which no-longer ships 'distutils'
        # out of the box. 'setuptools' package provides 'distutils'.
        if: ${{ runner.os == 'Windows' }}
        run: |
          python3 -m venv CI_venv
          CI_venv\Scripts\activate.bat
          python3 -m pip install setuptools
      - name: Install windows-build-tools
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm config set msvs_version 2019
      - name: Pre-warm the node headers cache for node-gyp
        if: ${{ runner.os == 'Windows' }}
        run: npx node-gyp install
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
